### ISSUE TITLE
Proxy compatible with B4J web apps.

### ISSUE THREAD

**Issue by AstralGeek33** [oxboot/ox#2]
I've been looking for something to create proxies for B4J web apps. I use EasyEngine and the proxy works. This is an example B4J web app: http://hello.astralgeek33.com ; However, as you can see it doesn't work because appears that I also need to [proxy TCP and UDP](https://www.b4x.com/android/forum/threads/web-app-proxy.80761/#post-520791).

Questions:
1: Could you make ox be able to create proxies that are compatible with B4J web apps? Maybe something like "sudo ox site:create webapp.tld --proxy=IP:PORT --b4j"?

2: If implemented I plan on using this in a commercial product and would like know where I can send some donations.

**Comment by zorca** [comment]
Ox is still at the very beginning of its development. I plan on expanding its functionality, but at the moment the first plans to make basic functionality, as EasyEngine: creation and deletion of sites, work with the database. But I will consider your offer and put it in the development plan.

**Comment by zorca** [comment]
I added a button for donations to develop the project: https://github.com/oxboot/ox
